package ru.sberbank.jd.enums;

public enum BotState {
    DEFAULT,
    WAITING_NEW_USER_FIO,
    WAITING_START_DATE,
    WAITING_END_DATE,
    WAITING_NEW_USER_TELEGRAMNAME, WAITING_VACATION_TO_DELETE
}
